image: hwrunner:latest
variables:
    GIT_SSL_NO_VERIFY: "true"
<<<<<<< HEAD
    EXEC: sfmm
    HW_DIR: hw3
=======
    EXEC: deet
    HW_DIR: hw4
    PROC_LIMIT: 200
>>>>>>> HW4_CODE/master
    CPU_LIMIT: 60
    FILE_LIMIT: 1000000
before_script:
    - make clean all -C ${HW_DIR}
stages:
    - build
    - run
    - test
build:
    stage: build
    script:
        - echo "Build done"
run:
    stage: run
    script:
<<<<<<< HEAD
=======
        - ulimit -u ${PROC_LIMIT}
>>>>>>> HW4_CODE/master
        - ulimit -t ${CPU_LIMIT}
        - ulimit -f ${FILE_LIMIT}
        - cd ${HW_DIR} && bin/${EXEC}
test:
    stage: test
    script:
<<<<<<< HEAD
        - ulimit -t ${CPU_LIMIT}
        - ulimit -f ${FILE_LIMIT}
        - cd ${HW_DIR} && bin/${EXEC}_tests -S --verbose=0 --timeout 30
=======
        - ulimit -u ${PROC_LIMIT}
        - ulimit -t ${CPU_LIMIT}
        - ulimit -f ${FILE_LIMIT}
        - cd ${HW_DIR} && bin/${EXEC}_tests -S -j1 --verbose=0 --timeout 60
>>>>>>> HW4_CODE/master
